from __future__ import annotations

from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

from agent_brain.integrations.actuator_client import ActuatorClient
from agent_brain.integrations.formal_verifier_client import FormalVerifierClient
from agent_brain.integrations.policy_client import PolicyMCPClient
from agent_brain.models import (
    DebateState,
    DefenseStrategy,
    ExecutionConstraint,
    FinalDecision,
    ImpactLevel,
    NextAction,
    RiskLevel,
    SecurityEvent,
    StrategyImpact,
    StrategyStatus,
    TopologyContext,
)
from agent_brain.services.llm import LLMClient
from agent_brain.workflows.debate_workflow import DebateWorkflow


class DebateOrchestrator:
    def __init__(
        self,
        llm: LLMClient,
        verifier_client: FormalVerifierClient | None = None,
        actuator_client: ActuatorClient | None = None,
        policy_client: PolicyMCPClient | None = None,
    ) -> None:
        # ``policy_client`` is optional: when omitted the workflow keeps
        # running exactly as before. When provided it is forwarded into
        # the Coordinator so that the final approval step also includes
        # a policy / business-impact validation pass.
        self.workflow = DebateWorkflow(llm, policy_client=policy_client)
        self.verifier_client = verifier_client or FormalVerifierClient()
        self.actuator_client = actuator_client or ActuatorClient()

    def process_event(self, event: SecurityEvent) -> dict:
        state = DebateState(
            debateId=f"deb-{uuid4()}",
            securityEvent=event,
            retrievedContext=["baseline policy set", "recent incident summary"],
            round=0,
        )
        final_state = self.workflow.run(state)
        strategy = final_state.revisedProposal or final_state.plannerProposal
        if strategy is None:
            raise RuntimeError("No strategy generated by workflow")
        next_action = final_state.finalDecision.nextAction if final_state.finalDecision else NextAction.STOP
        # Phase 3: only ``approved_for_execution`` strategies are eligible
        # to run formal verification + actuator execution. Anything that
        # the Coordinator marked as ``needs_revision`` / ``requires_approval``
        # must short-circuit here even if ``nextAction`` is ENTER_VERIFICATION.
        coordinator_status = (
            final_state.finalDecision.status
            if final_state.finalDecision
            else StrategyStatus.PENDING_VALIDATION
        )
        # Phase 5: also respect ``auto_execution_allowed``: when human approval
        # is required the orchestrator must NOT auto-trigger formal verification
        # nor actuator-service. The dashboard / human approver re-enters the
        # flow explicitly through Actuator MCP.
        auto_execution_allowed = (
            bool(final_state.finalDecision.autoExecutionAllowed)
            if final_state.finalDecision
            else False
        )
        should_verify = (
            next_action == NextAction.ENTER_VERIFICATION
            and coordinator_status == StrategyStatus.APPROVED_FOR_EXECUTION
            and auto_execution_allowed
        )
        verification = self.verifier_client.verify(strategy) if should_verify else {
            "passed": False,
            "reason": (
                f"skipped_due_to_{coordinator_status.value}"
                if coordinator_status != StrategyStatus.APPROVED_FOR_EXECUTION
                else f"skipped_due_to_{next_action.value}"
            ),
            "warnings": [],
            "violatedConstraints": [],
            "suggestedFixes": [],
        }
        verification_passed = verification.passed if should_verify else verification.get("passed", False)
        actuator_resp = (
            self.actuator_client.submit_strategy(strategy)
            if should_verify and verification_passed
            else {"status": "SKIPPED"}
        )
        # 同时输出旧字段（向后兼容）+ 新增 coordinatorDecision（snake_case 8 个 key）
        coordinator_decision = self._build_coordinator_decision(
            strategy=strategy, decision=final_state.finalDecision
        )
        return {
            "eventId": event.eventId,
            "processedAt": datetime.now(UTC).isoformat(),
            "debateState": final_state.model_dump(mode="json"),
            "finalStrategy": strategy.model_dump(mode="json"),
            "unresolvedChallenges": [c.model_dump(mode="json") for c in final_state.unresolvedChallenges],
            "nextAction": next_action.value,
            "decisionReason": final_state.finalDecision.decisionReason if final_state.finalDecision else "unknown",
            "verification": verification if isinstance(verification, dict) else verification.model_dump(mode="json"),
            "actuatorResponse": actuator_resp,
            # 新增字段：完整聚合 Coordinator 输出，按 spec 使用 snake_case
            "coordinatorDecision": coordinator_decision,
        }

    @staticmethod
    def _build_coordinator_decision(
        *, strategy: DefenseStrategy, decision: FinalDecision | None
    ) -> dict[str, Any]:
        """Build the unified Coordinator output consumed by dashboard-ui.

        Stable key set (snake_case so the FE can use it directly):

          - final_strategy
          - decision_reasoning
          - risk_level
          - confidence
          - topology_context_summary
          - mcp_trace                       (empty array when no MCP was called)
          - rollback_plan
          - execution_constraints
          - status                          (Phase 3: policy validation outcome)
          - human_approval_required         (Phase 3)
          - policy_validation               (Phase 3: full policy MCP envelope)
          - auto_execution_allowed          (Phase 5: human-approval boundary)
          - approval_reason                 (Phase 5)
          - safety_checks                   (Phase 5)

        ``final_strategy`` is enriched with the Coordinator-derived fields
        (``status`` / ``human_approval_required`` / ``auto_execution_allowed``
        / ``approval_reason`` / ``execution_constraints`` / ``safety_checks``)
        so the UI / Actuator MCP can read them without a join. The original
        DefenseStrategy Pydantic model is not modified, so the legacy
        ``finalStrategy`` field stays backward compatible.
        """
        # Stable rollback_plan dict (snake_case) reused across both branches.
        rollback_plan_dict = (
            strategy.rollbackPlan.model_dump(mode="json")
            if strategy.rollbackPlan
            else None
        )

        if decision is None:
            base_strategy = strategy.model_dump(mode="json")
            base_strategy["status"] = StrategyStatus.PENDING_VALIDATION.value
            base_strategy["human_approval_required"] = False
            # Phase 5: never auto-execute when Coordinator has not produced a decision.
            base_strategy["auto_execution_allowed"] = False
            base_strategy["approval_reason"] = []
            base_strategy["execution_constraints"] = []
            base_strategy["safety_checks"] = []
            # ---- Phase 6: unified MCP data model (snake_case mirror) ----
            # Strategy summary fields aligned with FinalStrategy schema so the
            # FE can read everything from final_strategy without a join.
            DebateOrchestrator._project_phase6_fields(
                target=base_strategy,
                strategy=strategy,
                rollback_plan_dict=rollback_plan_dict,
                topology_context_summary={},
                mcp_trace=[],
                execution_constraints=[],
                risk_level=RiskLevel.LOW,
            )
            return {
                "final_strategy": base_strategy,
                "decision_reasoning": "",
                "risk_level": "low",
                "confidence": float(strategy.confidence),
                "topology_context_summary": {},
                "mcp_trace": [],
                "rollback_plan": rollback_plan_dict,
                "execution_constraints": [],
                "status": StrategyStatus.PENDING_VALIDATION.value,
                "human_approval_required": False,
                "policy_validation": {
                    "valid": True,
                    "violations": [],
                    "warnings": [],
                    "requires_human_approval": False,
                    "suggestions": [],
                    "mcp_called": False,
                    "mcp_error": None,
                },
                # Phase 5 envelope additions
                "auto_execution_allowed": False,
                "approval_reason": [],
                "safety_checks": [],
            }
        # Project the Coordinator-decided fields onto the strategy snapshot
        # so the FE can read ``coordinatorDecision.final_strategy.status``
        # without a separate join.
        enriched_strategy = strategy.model_dump(mode="json")
        enriched_strategy["status"] = decision.status.value
        enriched_strategy["human_approval_required"] = bool(decision.humanApprovalRequired)
        # Phase 5 projection onto final_strategy: required by spec so the FE
        # and Actuator MCP can read all gating signals from one place.
        enriched_strategy["auto_execution_allowed"] = bool(decision.autoExecutionAllowed)
        enriched_strategy["approval_reason"] = list(decision.approvalReason or [])
        enriched_strategy["execution_constraints"] = list(decision.executionConstraints or [])
        enriched_strategy["safety_checks"] = [
            c.model_dump(mode="json") for c in (decision.safetyChecks or [])
        ]

        # ---- Phase 6: unified MCP data model (snake_case mirror) ----
        topology_summary = dict(decision.topologyContextSummary or {})
        mcp_trace_dump = [c.model_dump(mode="json") for c in (decision.mcpTrace or [])]
        execution_constraints_list = list(decision.executionConstraints or [])
        DebateOrchestrator._project_phase6_fields(
            target=enriched_strategy,
            strategy=strategy,
            rollback_plan_dict=rollback_plan_dict,
            topology_context_summary=topology_summary,
            mcp_trace=mcp_trace_dump,
            execution_constraints=execution_constraints_list,
            risk_level=decision.riskLevel,
        )

        return {
            "final_strategy": enriched_strategy,
            "decision_reasoning": decision.decisionReasoning or decision.rationale,
            "risk_level": decision.riskLevel.value,
            "confidence": float(strategy.confidence),
            "topology_context_summary": topology_summary,
            "mcp_trace": mcp_trace_dump,
            "rollback_plan": rollback_plan_dict,
            "execution_constraints": execution_constraints_list,
            "status": decision.status.value,
            "human_approval_required": bool(decision.humanApprovalRequired),
            "policy_validation": decision.policyValidation.model_dump(mode="json"),
            # Phase 5 envelope additions
            "auto_execution_allowed": bool(decision.autoExecutionAllowed),
            "approval_reason": list(decision.approvalReason or []),
            "safety_checks": [
                c.model_dump(mode="json") for c in (decision.safetyChecks or [])
            ],
        }

    @staticmethod
    def _project_phase6_fields(
        *,
        target: dict[str, Any],
        strategy: DefenseStrategy,
        rollback_plan_dict: dict[str, Any] | None,
        topology_context_summary: dict[str, Any],
        mcp_trace: list[dict[str, Any]],
        execution_constraints: list[str],
        risk_level: RiskLevel,
    ) -> None:
        """Project unified Phase 6 (MCP data model) fields onto a final_strategy dict.

        Adds the ``snake_case`` fields required by the unified contract while
        preserving every existing camelCase field (DefenseStrategy schema) so
        the legacy API stays backward compatible. Specifically writes:
            strategy_id / action / target / ttl_minutes / rollback_plan /
            topology_context_summary / mcp_trace / topology_context /
            strategy_impact / execution_constraints_detailed
        """
        # 1) snake_case primary identifiers required by the FinalStrategy spec
        target["strategy_id"] = strategy.strategyId
        # ``action`` and ``target`` are singular projections of the dominant
        # DefenseAction (actions[0]); the full list stays under ``actions``.
        primary_action = strategy.actions[0] if strategy.actions else None
        target["action"] = primary_action.type.value if primary_action else None
        target["target"] = primary_action.target if primary_action else None

        # 2) TTL minute-level mirror (DefenseStrategy.ttl is seconds-based).
        ttl_seconds = int(strategy.ttl) if strategy.ttl else 0
        target["ttl_minutes"] = ttl_seconds // 60 if ttl_seconds > 0 else None

        # 3) snake_case rollback_plan / topology_context_summary / mcp_trace
        target["rollback_plan"] = rollback_plan_dict
        target["topology_context_summary"] = dict(topology_context_summary)
        target["mcp_trace"] = list(mcp_trace)

        # 4) Structured TopologyContext projection (Phase 6).
        target["topology_context"] = DebateOrchestrator._build_topology_context(
            topology_context_summary
        ).model_dump(mode="json")

        # 5) Structured StrategyImpact projection (Phase 6).
        target["strategy_impact"] = DebateOrchestrator._build_strategy_impact(
            strategy=strategy,
            topology_context_summary=topology_context_summary,
            risk_level=risk_level,
        ).model_dump(mode="json")

        # 6) Structured ExecutionConstraint list (Phase 6) - parallel to
        #    the existing string list, never replacing it.
        target["execution_constraints_detailed"] = [
            ExecutionConstraint(text=line).model_dump(mode="json")
            for line in execution_constraints
        ]

    @staticmethod
    def _build_topology_context(summary: dict[str, Any]) -> TopologyContext:
        """Convert the loose ``topologyContextSummary`` dict into a typed TopologyContext.

        Tolerates missing fields - any absent key falls back to a safe empty default.
        """
        red_team = summary.get("red_team") or {}
        return TopologyContext(
            topology_context_used=bool(summary.get("topology_context_used", False)),
            expected_blast_radius=summary.get("expected_blast_radius") or None,
            affected_assets=list(summary.get("affected_assets") or []),
            topology_evidence=list(summary.get("topology_evidence") or []),
            topology_findings=list(red_team.get("topology_findings") or []),
            residual_attack_paths=list(red_team.get("residual_attack_paths") or []),
            business_impact_risks=list(red_team.get("business_impact_risks") or []),
            recommended_constraints=list(red_team.get("recommended_constraints") or []),
            mcp_errors=list(summary.get("mcp_errors") or []),
        )

    @staticmethod
    def _build_strategy_impact(
        *,
        strategy: DefenseStrategy,
        topology_context_summary: dict[str, Any],
        risk_level: RiskLevel,
    ) -> StrategyImpact:
        """Derive a StrategyImpact summary from existing signals.

        impact_level mirrors expected_blast_radius when known, otherwise
        falls back to the risk_level value (low/medium/high/critical).
        """
        blast = topology_context_summary.get("expected_blast_radius")
        # Map blast radius -> impact level enum (treat 'high' as ImpactLevel.HIGH).
        impact_map = {
            "low": ImpactLevel.LOW,
            "medium": ImpactLevel.MEDIUM,
            "high": ImpactLevel.HIGH,
        }
        if blast in impact_map:
            impact_level = impact_map[blast]
        else:
            # Fall back to risk_level so the FE always gets a non-NONE value
            # whenever Coordinator computed a meaningful risk.
            try:
                impact_level = ImpactLevel(risk_level.value)
            except ValueError:
                impact_level = ImpactLevel.NONE

        red_team = topology_context_summary.get("red_team") or {}
        residual_paths = list(red_team.get("residual_attack_paths") or [])
        affected_assets = list(topology_context_summary.get("affected_assets") or [])
        # Combine planner-affected assets with strategy.scope.assets for completeness.
        for asset in (strategy.scope.assets if strategy.scope else []):
            if asset not in affected_assets:
                affected_assets.append(asset)

        return StrategyImpact(
            impact_level=impact_level,
            risk_level=risk_level,
            expected_blast_radius=blast or None,
            affected_assets=affected_assets,
            affected_paths=[p.get("summary", "") for p in residual_paths if isinstance(p, dict)],
            residual_path_count=len(residual_paths),
            business_impact_count=len(red_team.get("business_impact_risks") or []),
            rationale=(
                f"impact={impact_level.value}; risk={risk_level.value}; "
                f"residual_paths={len(residual_paths)}"
            ),
        )

