from __future__ import annotations

import asyncio
import json
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from agent_brain.integrations.policy_client import PolicyMCPClient
from agent_brain.models import (
    ActionType,
    BlastRadius,
    DebateState,
    DebateStatus,
    DebateTurn,
    DecisionType,
    DefenseStrategy,
    FinalDecision,
    MCPToolCall,
    NextAction,
    PlannerTopologyMetadata,
    PolicyValidation,
    RedTeamFindings,
    RiskLevel,
    SafetyCheck,
    Severity,
    StrategyStatus,
)
from agent_brain.services.llm import LLMClient


def _load_prompt(name: str) -> str:
    prompt_path = Path(__file__).resolve().parent.parent / "prompts" / name
    return prompt_path.read_text(encoding="utf-8")


# 风险等级数值化，便于多维信号取最大值
_RISK_ORDER = {
    RiskLevel.LOW: 0,
    RiskLevel.MEDIUM: 1,
    RiskLevel.HIGH: 2,
    RiskLevel.CRITICAL: 3,
}
_RISK_REVERSE = {v: k for k, v in _RISK_ORDER.items()}


# Severity tags that count as a hard blocker on the policy side. ``high`` and
# ``critical`` violations cause the strategy to require revision; medium / low
# findings only land in ``warnings`` and never set ``valid=False``.
_BLOCKING_VIOLATION_SEVERITIES = {"critical", "high"}


class CoordinatorAgent:
    def __init__(
        self,
        llm: LLMClient,
        policy_client: PolicyMCPClient | None = None,
    ) -> None:
        """Coordinator with optional Policy MCP integration.

        ``policy_client`` is fully optional: when omitted the agent falls
        back to the original behavior and emits an empty ``policyValidation``
        block, keeping all upstream tests untouched.
        """
        self.llm = llm
        self.system_prompt = _load_prompt("coordinator_prompt.txt")
        self.policy_client = policy_client

    # ------------------------------------------------------------------
    # 主入口
    # ------------------------------------------------------------------

    def run(self, state: DebateState) -> DebateState:
        # 在 LLM user_prompt 中注入聚合后的拓扑信号，便于真实 LLM 协同推理
        revised_json = (
            state.revisedProposal.model_dump_json() if state.revisedProposal else "{}"
        )
        topology_summary = self._build_topology_context_summary(state)
        mcp_trace = self._aggregate_mcp_trace(state)
        execution_constraints = self._build_execution_constraints(state)
        _ = self.llm.generate(
            system_prompt=self.system_prompt,
            user_prompt=(
                f"revised={revised_json}; "
                f"topologySummary={topology_summary}; "
                f"mcpTraceSize={len(mcp_trace)}"
            ),
        )

        strategy = state.revisedProposal or state.plannerProposal
        if strategy is None:
            state.finalDecision = FinalDecision(
                decision=DecisionType.REJECT,
                owner="Coordinator",
                rationale="No strategy generated by upstream agents",
                nextAction=NextAction.STOP,
                unresolvedChallenges=state.unresolvedChallenges,
                decisionReason="empty_strategy",
                decidedAt=datetime.now(UTC),
                # 拓扑/MCP 扩展字段
                riskLevel=RiskLevel.LOW,
                decisionReasoning="No upstream strategy was generated; cannot proceed.",
                topologyContextSummary=topology_summary,
                mcpTrace=mcp_trace,
                executionConstraints=execution_constraints,
                # Phase 3: empty-strategy path is a hard reject; no policy validation possible.
                status=StrategyStatus.REJECTED,
                humanApprovalRequired=False,
                policyValidation=PolicyValidation(),
                # Phase 5: rejected strategies must never auto-execute.
                autoExecutionAllowed=False,
                approvalReason=["No upstream strategy was generated; cannot proceed"],
                safetyChecks=[],
            )
            state.status = DebateStatus.CLOSED
            return state

        dedup_removed = self._deduplicate_strategy_actions(strategy)
        if dedup_removed > 0:
            dedup_note = f"[Coordinator] deduplicated_actions_count={dedup_removed}"
            strategy.rationale = (strategy.rationale.rstrip() + "\n\n" + dedup_note).strip()
            execution_constraints.append(f"deduplicated_actions_count={dedup_removed}")

        unresolved_count = len(state.unresolvedChallenges)
        high_risk = state.securityEvent.riskScore >= state.highRiskThreshold
        confidence_ok = strategy.confidence >= state.confidenceThreshold
        reached_max_round = state.round >= state.maxRounds

        next_action = NextAction.CONTINUE_DEBATE
        decision = DecisionType.NEED_MORE_EVIDENCE
        reason = "need_more_coverage"
        rationale = "继续博弈以覆盖剩余挑战。"

        if high_risk and not confidence_ok:
            next_action = NextAction.REQUEST_HUMAN_REVIEW
            decision = DecisionType.ESCALATE
            reason = "high_risk_low_confidence"
            rationale = "风险高且策略置信度不足，转人工确认。"
        elif unresolved_count == 0 and confidence_ok:
            next_action = NextAction.ENTER_VERIFICATION
            decision = DecisionType.APPROVE
            reason = "coverage_good_confidence_good"
            rationale = "主要挑战已覆盖且置信度达标，进入验证层。"
        elif reached_max_round:
            next_action = NextAction.ENTER_VERIFICATION if confidence_ok else NextAction.REQUEST_HUMAN_REVIEW
            decision = DecisionType.APPROVE if confidence_ok else DecisionType.ESCALATE
            reason = "max_round_reached"
            rationale = "达到最大轮数，按当前置信度做收敛决策。"

        if next_action == NextAction.CONTINUE_DEBATE:
            state.round += 1
            state.status = DebateStatus.IN_PROGRESS
        else:
            state.status = DebateStatus.CLOSED
            if strategy:
                strategy.approved = next_action == NextAction.ENTER_VERIFICATION

        # Phase 3: run policy MCP validation as the last gate before approval.
        # This call is best-effort: any failure is captured into a fallback
        # ``PolicyValidation`` and surfaced through ``mcp_error`` so the rest
        # of the workflow keeps working.
        policy_validation, policy_calls = self._run_policy_validation(strategy)
        mcp_trace.extend(policy_calls)

        # Aggregate multi-signal risk level (may cap sandbox residual paths below HIGH).
        risk_level = self._compute_risk_level(state, strategy)

        low_risk_auto = self._is_low_risk_auto_executable(
            state=state,
            strategy=strategy,
            policy_validation=policy_validation,
            risk_level=risk_level,
        )

        # Sandbox / demo events: force verification path when predicates match (see helper).
        if low_risk_auto:
            next_action = NextAction.ENTER_VERIFICATION
            decision = DecisionType.APPROVE
            reason = "low_risk_sandbox_auto_executable"
            rationale = (
                "Low-risk sandbox path: policy validated, blast radius LOW, "
                "eligible for automated verification and execution."
            )
            state.status = DebateStatus.CLOSED
            strategy.approved = True

        # Phase 3: derive strategy status + human-approval flag from
        # (a) the upstream debate decision and (b) the policy validation.
        status = self._resolve_strategy_status(
            next_action=next_action,
            decision_type=decision,
            policy_validation=policy_validation,
        )
        human_approval_required = self._resolve_human_approval(
            next_action=next_action,
            policy_validation=policy_validation,
            risk_level=risk_level,
        )

        # Phase 5: 6 项独立的人工确认边界检查。任一未通过即强制升级人工审批。
        safety_checks = self._evaluate_safety_checks(
            strategy=strategy,
            state=state,
            risk_level=risk_level,
            policy_validation=policy_validation,
        )
        forced_by_safety = any(not c.passed for c in safety_checks)
        if forced_by_safety:
            if not low_risk_auto:
                human_approval_required = True
                # Downgrade status only when auto-exec was implied:
                if status == StrategyStatus.APPROVED_FOR_EXECUTION:
                    status = StrategyStatus.REQUIRES_APPROVAL

        # Sandbox low-risk auto path may bypass safety vetoes when predicates matched earlier.
        if low_risk_auto:
            human_approval_required = False
            status = StrategyStatus.APPROVED_FOR_EXECUTION

        # Phase 5: auto_execution_allowed 必须同时满足两个硬条件：
        #   1) 不需要人工审批
        #   2) status 仍是 APPROVED_FOR_EXECUTION
        # 任何一条不满足都禁止自动执行。
        auto_execution_allowed = (
            not human_approval_required
            and status == StrategyStatus.APPROVED_FOR_EXECUTION
        )

        # Phase 5: 收集人工审批原因（只看 passed=False 的检查项 + 状态级原因）。
        approval_reason = self._collect_approval_reasons(
            safety_checks=safety_checks,
            status=status,
            policy_validation=policy_validation,
        )

        # Append policy-driven execution constraints. Only push when the
        # respective signal is actually triggered, otherwise we keep the
        # constraint list lean and easy to render on the UI.
        self._append_policy_execution_constraints(
            execution_constraints,
            status=status,
            human_approval_required=human_approval_required,
            policy_validation=policy_validation,
        )

        # Phase 5: 把"需要人工审批"作为最强约束写到 execution_constraints，
        # 让执行链 / Actuator MCP 直接看到禁止自动执行的硬约束。
        self._append_human_approval_constraints(
            execution_constraints,
            human_approval_required=human_approval_required,
            auto_execution_allowed=auto_execution_allowed,
            approval_reasons=approval_reason,
        )

        # Once we know the strategy must be revised or held for approval,
        # ``approved`` on the underlying DefenseStrategy MUST NOT stay True
        # even if the upstream decision was APPROVE.
        if strategy and status in (
            StrategyStatus.NEEDS_REVISION,
            StrategyStatus.REQUIRES_APPROVAL,
            StrategyStatus.REJECTED,
        ):
            strategy.approved = False

        decision_reasoning = self._build_decision_reasoning(
            rationale=rationale,
            reason=reason,
            unresolved_count=unresolved_count,
            confidence_ok=confidence_ok,
            high_risk=high_risk,
            risk_level=risk_level,
            findings=state.redTeamFindings,
            metadata=state.plannerMetadata,
            status=status,
            policy_validation=policy_validation,
            safety_checks=safety_checks,
            auto_execution_allowed=auto_execution_allowed,
            human_approval_required=human_approval_required,
        )

        state.finalDecision = FinalDecision(
            decision=decision,
            owner="Coordinator",
            rationale=rationale,
            nextAction=next_action,
            unresolvedChallenges=state.unresolvedChallenges,
            decisionReason=reason,
            decidedAt=datetime.now(UTC),
            riskLevel=risk_level,
            decisionReasoning=decision_reasoning,
            topologyContextSummary=topology_summary,
            mcpTrace=mcp_trace,
            executionConstraints=execution_constraints,
            status=status,
            humanApprovalRequired=human_approval_required,
            policyValidation=policy_validation,
            # ---- Phase 5: human-approval boundary projection ----
            autoExecutionAllowed=auto_execution_allowed,
            approvalReason=approval_reason,
            safetyChecks=safety_checks,
        )
        # 兼容直接喂入 Coordinator 的测试场景；真实工作流由 Planner 把 round 推到 >= 1
        state.history.append(
            DebateTurn(
                round=max(1, state.round),
                actor="Coordinator",
                message=(
                    f"Decision={decision.value}, nextAction={next_action.value}, "
                    f"unresolved={unresolved_count}, risk={risk_level.value}, "
                    f"status={status.value}, mcpTrace={len(mcp_trace)}"
                ),
                timestamp=datetime.now(UTC),
            )
        )
        return state

    # ------------------------------------------------------------------
    # DefenseStrategy.actions deduplication (before policy / safety gates)
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize_egress_policy_category(parameters: dict[str, Any]) -> str:
        """Bucket RESTRICT_EGRESS policy strings into a stable semantic category."""
        raw = str(parameters.get("policy", "") or "").lower().replace("-", "_")
        # Broad deny/block semantics collapse together even when wording differs.
        if any(
            tok in raw
            for tok in (
                "deny",
                "block",
                "denyuntrusted",
                "deny_untrusted",
                "deny_all",
                "blackhole",
            )
        ):
            return "egress_deny_or_block"
        if any(tok in raw for tok in ("observe", "tighten", "monitor", "watch")):
            return "egress_observe_or_tighten"
        return raw if raw else "egress_default"

    @staticmethod
    def _egress_strictness_score(parameters: dict[str, Any]) -> int:
        """Higher score == stricter egress intent for tie-breaking."""
        raw = str(parameters.get("policy", "") or "").lower()
        score = 55
        if any(tok in raw for tok in ("deny", "block", "blackhole")):
            score = 100
            if "all" in raw or "deny_all" in raw:
                score = 110
        elif any(tok in raw for tok in ("observe", "tighten", "monitor")):
            score = 38
        orig = parameters.get("originalAction")
        if orig == "BLOCK_IP":
            score = max(score, 95)
        return score

    def _deduplicate_strategy_actions(self, strategy: DefenseStrategy) -> int:
        """Collapse redundant actions on the Coordinator-bound strategy.

        - RESTRICT_EGRESS: keyed by (type, target, normalized policy category). Keeps
          the strictest intent; ties favor the later action (revision wins).
        - ALERT_ONLY: removed only when identical (same target + normalized params).
        - Other types: identical DefenseAction fingerprints collapse to the last entry.

        Returns how many actions were removed.
        """
        actions = strategy.actions
        n = len(actions)
        if n <= 1:
            return 0

        keep: set[int] = set(range(n))

        # 1) RESTRICT_EGRESS groups per (target, policy category)
        egress_groups: dict[tuple[str, str], list[int]] = defaultdict(list)
        for i, act in enumerate(actions):
            if act.type != ActionType.RESTRICT_EGRESS:
                continue
            cat = self._normalize_egress_policy_category(act.parameters or {})
            egress_groups[(act.target, cat)].append(i)

        for idxs in egress_groups.values():
            if len(idxs) <= 1:
                continue
            best = idxs[0]
            best_score = self._egress_strictness_score(actions[best].parameters or {})
            for j in idxs[1:]:
                sj = self._egress_strictness_score(actions[j].parameters or {})
                if sj > best_score or (sj == best_score and j > best):
                    best = j
                    best_score = sj
            for j in idxs:
                if j != best:
                    keep.discard(j)

        # 2) ALERT_ONLY exact duplicates — keep the last occurrence only
        alert_buckets: dict[tuple[str, str], list[int]] = defaultdict(list)
        for i, act in enumerate(actions):
            if act.type != ActionType.ALERT_ONLY:
                continue
            fp = json.dumps(act.parameters or {}, sort_keys=True)
            alert_buckets[(act.target, fp)].append(i)
        for idxs in alert_buckets.values():
            if len(idxs) <= 1:
                continue
            for j in idxs[:-1]:
                keep.discard(j)

        # 3) Other action types — collapse identical fingerprints, keep last
        other_buckets: dict[tuple[Any, ...], list[int]] = defaultdict(list)
        for i, act in enumerate(actions):
            if act.type in (ActionType.RESTRICT_EGRESS, ActionType.ALERT_ONLY):
                continue
            fp = (
                act.type.value,
                act.target,
                json.dumps(act.parameters or {}, sort_keys=True),
            )
            other_buckets[fp].append(i)
        for idxs in other_buckets.values():
            if len(idxs) <= 1:
                continue
            for j in idxs[:-1]:
                keep.discard(j)

        kept_sorted = sorted(keep)
        new_actions = [actions[i] for i in kept_sorted]
        removed = n - len(new_actions)
        strategy.actions = new_actions
        return removed

    # ------------------------------------------------------------------
    # Phase 3: Policy MCP integration
    # ------------------------------------------------------------------

    def _run_policy_validation(
        self, strategy: DefenseStrategy
    ) -> tuple[PolicyValidation, list[MCPToolCall]]:
        """Call ``validate_strategy`` over policy-mcp-server.

        Returns a ``(PolicyValidation, list[MCPToolCall])`` tuple. The
        client is invoked through a synchronous bridge (``asyncio.run``)
        so the rest of the agent stays sync. When the client is missing
        or disabled we return a benign empty validation marked with
        ``mcp_called=False`` so downstream consumers can tell "did not
        run" apart from "ran and passed".
        """
        if self.policy_client is None or not self.policy_client.enabled:
            return PolicyValidation(mcp_called=False), []

        # Best-effort serialization. ``mode='json'`` produces JSON-safe
        # primitives and matches what an external service would receive.
        try:
            strategy_dict = strategy.model_dump(mode="json")
        except Exception as exc:  # extremely unlikely, but never crash here
            return (
                PolicyValidation(
                    mcp_called=False, mcp_error=f"strategy serialization failed: {exc}"
                ),
                [],
            )

        envelope = self._invoke_policy_tool("validate_strategy", strategy_dict)

        # Build the ``MCPToolCall`` trace entry regardless of success.
        call = MCPToolCall(
            server="policy-mcp-server",
            tool="validate_strategy",
            arguments={"strategyId": strategy.strategyId},
            success=bool(envelope.get("success")),
            summary=str(envelope.get("message") or ""),
        )

        if not envelope.get("success"):
            return (
                PolicyValidation(
                    mcp_called=True,
                    mcp_error=str(envelope.get("message") or "policy mcp call failed"),
                ),
                [call],
            )

        data = envelope.get("data") or {}
        return (
            PolicyValidation(
                valid=bool(data.get("valid", True)),
                violations=list(data.get("violations") or []),
                warnings=list(data.get("warnings") or []),
                requires_human_approval=bool(data.get("requires_human_approval", False)),
                suggestions=list(data.get("suggestions") or []),
                mcp_called=True,
                mcp_error=None,
            ),
            [call],
        )

    def _invoke_policy_tool(
        self, tool: str, strategy_dict: dict[str, Any]
    ) -> dict[str, Any]:
        """Run a single policy-MCP tool call from a sync context.

        We intentionally use ``asyncio.run`` + a fresh client lifecycle
        per call: this is fine because the coordinator runs at most once
        per debate and avoids leaking a long-lived background loop.
        Tests can override this method to short-circuit the dispatch.
        """

        async def _invoke() -> dict[str, Any]:
            assert self.policy_client is not None
            method = getattr(self.policy_client, tool)
            try:
                return await method(strategy_dict)
            finally:
                # The client supports being reused; only the AsyncExitStack
                # holds resources in real mode. Closing here keeps tests
                # deterministic without forcing an ``async with`` block.
                await self.policy_client.aclose()

        try:
            return asyncio.run(_invoke())
        except RuntimeError as exc:
            # ``asyncio.run`` cannot be called from inside a running loop;
            # callers that already have one should subclass and override.
            return {
                "success": False,
                "data": None,
                "message": f"policy mcp invocation failed: {exc}",
            }

    @staticmethod
    def _resolve_strategy_status(
        *,
        next_action: NextAction,
        decision_type: DecisionType,
        policy_validation: PolicyValidation,
    ) -> StrategyStatus:
        """Pick the strategy status that the executor / UI should rely on.

        Decision table (top match wins):

        +------------------------------------------+-------------------------+
        | Condition                                | Resulting status        |
        +==========================================+=========================+
        | upstream rejected                        | REJECTED                |
        | policy validation ran and is invalid     | NEEDS_REVISION          |
        | policy validation requires human approval| REQUIRES_APPROVAL       |
        | upstream debate asked for human review   | REQUIRES_APPROVAL       |
        | upstream debate is still mid-flight      | PENDING_VALIDATION      |
        | otherwise (approved for verification)    | APPROVED_FOR_EXECUTION  |
        +------------------------------------------+-------------------------+
        """
        if decision_type == DecisionType.REJECT:
            return StrategyStatus.REJECTED

        if policy_validation.mcp_called and not policy_validation.valid:
            return StrategyStatus.NEEDS_REVISION

        if policy_validation.mcp_called and policy_validation.requires_human_approval:
            return StrategyStatus.REQUIRES_APPROVAL

        if next_action == NextAction.REQUEST_HUMAN_REVIEW:
            return StrategyStatus.REQUIRES_APPROVAL

        if next_action == NextAction.ENTER_VERIFICATION:
            return StrategyStatus.APPROVED_FOR_EXECUTION

        # Still in debate (CONTINUE_DEBATE / STOP without a strategy escalate
        # path) -> we have not actually validated anything yet.
        return StrategyStatus.PENDING_VALIDATION

    @staticmethod
    def _resolve_human_approval(
        *,
        next_action: NextAction,
        policy_validation: PolicyValidation,
        risk_level: RiskLevel,
    ) -> bool:
        """``human_approval_required`` is the OR of three independent signals."""
        if policy_validation.mcp_called and policy_validation.requires_human_approval:
            return True
        if next_action == NextAction.REQUEST_HUMAN_REVIEW:
            return True
        if risk_level == RiskLevel.CRITICAL:
            return True
        return False

    @staticmethod
    def _append_policy_execution_constraints(
        constraints: list[str],
        *,
        status: StrategyStatus,
        human_approval_required: bool,
        policy_validation: PolicyValidation,
    ) -> None:
        """Push policy-driven sentences onto the existing constraint list.

        We never auto-replace existing entries from Red-Team or Planner;
        we only append. Order matters for the UI: the strongest "do not
        auto-execute" line is pushed first.
        """
        if status == StrategyStatus.NEEDS_REVISION:
            constraints.append(
                "Auto-execution blocked: policy-mcp-server validation failed; "
                "revise the strategy and resubmit before any execution"
            )
        elif status == StrategyStatus.REJECTED:
            constraints.append(
                "Auto-execution blocked: strategy rejected by Coordinator; "
                "no execution is permitted"
            )
        elif human_approval_required:
            constraints.append(
                "Auto-execution disabled: human approval is required before "
                "this strategy may be deployed"
            )

        if policy_validation.mcp_called:
            critical_violations = [
                v
                for v in policy_validation.violations
                if str(v.get("severity", "")).lower() == "critical"
            ]
            if critical_violations:
                ids = ", ".join(
                    sorted({str(v.get("rule_id", "")) for v in critical_violations if v.get("rule_id")})
                )
                constraints.append(
                    f"Critical policy violations must be resolved before deployment: {ids}"
                )

    # ------------------------------------------------------------------
    # Phase 5: human-approval boundary
    # ------------------------------------------------------------------

    # 6 项检查的稳定 id（与前端类型 / 测试断言对齐，请勿随意修改）。
    _CHECK_CRITICAL_ASSETS = "critical_assets_impacted"
    _CHECK_IMPACT_HIGH = "impact_level_high"
    _CHECK_DESTRUCTIVE_ACTION = "destructive_action_type"
    _CHECK_ROLLBACK_PRESENT = "rollback_plan_present"
    _CHECK_TTL_PRESENT = "ttl_minutes_present"
    _CHECK_POLICY_HUMAN_APPROVAL = "policy_human_approval_not_required"

    @classmethod
    def _evaluate_safety_checks(
        cls,
        *,
        strategy: DefenseStrategy,
        state: DebateState,
        risk_level: RiskLevel,
        policy_validation: PolicyValidation,
    ) -> list[SafetyCheck]:
        """Run the 6 mandatory human-approval boundary checks.

        Each check returns a ``SafetyCheck`` entry. ``passed=False`` means
        the corresponding trigger fired and human approval is required.
        Order is stable so the UI can render a deterministic list.
        """
        return [
            cls._check_critical_assets_impacted(state=state),
            cls._check_impact_level(state=state, risk_level=risk_level),
            cls._check_destructive_action(strategy=strategy),
            cls._check_rollback_plan(strategy=strategy),
            cls._check_ttl_minutes(strategy=strategy),
            cls._check_policy_human_approval(policy_validation=policy_validation),
        ]

    # ---- Individual checks --------------------------------------------------

    @classmethod
    def _check_critical_assets_impacted(cls, *, state: DebateState) -> SafetyCheck:
        """Detect whether the strategy touches any CRITICAL asset.

        Three independent signals are considered:
        1. Red-Team ``topology_based_findings`` mentions CRITICAL
        2. Red-Team ``business_impact_risks`` mentions CRITICAL
        3. SecurityEvent severity == CRITICAL (event-side fallback signal)

        Any positive signal trips the check.
        """
        ft = state.redTeamFindings
        topo_signal = bool(
            ft and any("CRITICAL" in (f or "").upper() for f in ft.topology_based_findings)
        )
        biz_signal = bool(
            ft and any("CRITICAL" in (r or "").upper() for r in ft.business_impact_risks)
        )
        severity_signal = state.securityEvent.severity == Severity.CRITICAL

        impacted = topo_signal or biz_signal or severity_signal
        if not impacted:
            detail = "No CRITICAL asset impact detected"
        else:
            reasons: list[str] = []
            if topo_signal:
                reasons.append("Red-Team topology findings flag CRITICAL assets")
            if biz_signal:
                reasons.append("Red-Team business-impact risks flag CRITICAL services")
            if severity_signal:
                reasons.append(f"event severity={state.securityEvent.severity.value}")
            detail = "; ".join(reasons)

        return SafetyCheck(
            id=cls._CHECK_CRITICAL_ASSETS,
            label="Critical assets impact",
            passed=not impacted,
            detail=detail,
        )

    @classmethod
    def _check_impact_level(
        cls, *, state: DebateState, risk_level: RiskLevel
    ) -> SafetyCheck:
        """Trip when expected blast radius is HIGH or risk_level is HIGH+."""
        blast = (
            state.plannerMetadata.expected_blast_radius
            if state.plannerMetadata
            else BlastRadius.LOW
        )
        is_high = blast == BlastRadius.HIGH or risk_level in (
            RiskLevel.HIGH,
            RiskLevel.CRITICAL,
        )
        return SafetyCheck(
            id=cls._CHECK_IMPACT_HIGH,
            label="Impact level high",
            passed=not is_high,
            detail=f"blast_radius={blast.value}, risk_level={risk_level.value}",
        )

    @classmethod
    def _check_destructive_action(cls, *, strategy: DefenseStrategy) -> SafetyCheck:
        """Trip when any action matches firewall_deny_all / isolate_host /
        scale_down_critical_service semantics.

        - ``ISOLATE_HOST``: always counts as ``isolate_host``
        - ``APPLY_FIREWALL_RULE`` without a 5-tuple (or with explicit
          ``action=deny_all``): counts as ``firewall_deny_all``
        - ``SCALE_PROTECTION`` whose params indicate scale-down or whose
          target name contains ``critical``: counts as
          ``scale_down_critical_service``
        """
        triggers: list[str] = []
        for action in strategy.actions:
            if action.type == ActionType.ISOLATE_HOST:
                triggers.append(f"isolate_host on {action.target}")
                continue
            if cls._is_firewall_deny_all(action):
                triggers.append(f"firewall_deny_all on {action.target}")
                continue
            if cls._is_scale_down_critical(action):
                triggers.append(f"scale_down_critical_service on {action.target}")
                continue

        if not triggers:
            return SafetyCheck(
                id=cls._CHECK_DESTRUCTIVE_ACTION,
                label="Destructive action type",
                passed=True,
                detail="No firewall_deny_all / isolate_host / scale_down_critical_service detected",
            )
        return SafetyCheck(
            id=cls._CHECK_DESTRUCTIVE_ACTION,
            label="Destructive action type",
            passed=False,
            detail="Strategy contains destructive action(s): " + "; ".join(triggers),
        )

    @staticmethod
    def _is_firewall_deny_all(action: Any) -> bool:
        """``APPLY_FIREWALL_RULE`` is treated as deny-all when:
        - its action mode is explicitly ``deny_all`` / ``deny-all``, OR
        - it lacks a usable 5-tuple (source, destination, port(s), protocol).
        """
        if action.type != ActionType.APPLY_FIREWALL_RULE:
            return False
        params = dict(action.parameters or {})
        mode = str(params.get("action") or params.get("mode") or "").lower()
        if mode in {"deny_all", "deny-all", "block_all", "block-all"}:
            return True
        has_source = bool(params.get("source") or params.get("sourceIp"))
        has_destination = bool(params.get("destination") or params.get("destIp"))
        has_port = bool(params.get("port") or params.get("ports"))
        has_protocol = bool(params.get("protocol"))
        return not (has_source and has_destination and has_port and has_protocol)

    @staticmethod
    def _is_scale_down_critical(action: Any) -> bool:
        """``SCALE_PROTECTION`` mapped to ``scale_down_critical_service`` when
        params hint at scale-down OR when target contains ``critical``."""
        if action.type != ActionType.SCALE_PROTECTION:
            return False
        params = dict(action.parameters or {})
        direction = str(params.get("direction") or "").lower()
        mode = str(params.get("mode") or "").lower()
        if direction == "down" or mode in {"scale_down", "scale-down"}:
            return True
        target = str(action.target or "").lower()
        if "critical" in target:
            return True
        replicas = params.get("replicas")
        if isinstance(replicas, (int, float)) and replicas <= 0:
            return True
        return False

    @classmethod
    def _check_rollback_plan(cls, *, strategy: DefenseStrategy) -> SafetyCheck:
        """A rollback plan must have at least one step AND a trigger condition.

        ``DefenseStrategy.rollbackPlan`` is required by Pydantic, but an
        empty steps list / blank trigger condition counts as effectively
        missing.
        """
        plan = strategy.rollbackPlan
        steps_ok = bool(plan and plan.steps)
        trigger_ok = bool(plan and (plan.triggerCondition or "").strip())
        present = steps_ok and trigger_ok
        if present:
            detail = f"plan_id={plan.planId}, steps={len(plan.steps)}"
        else:
            missing: list[str] = []
            if not steps_ok:
                missing.append("steps empty")
            if not trigger_ok:
                missing.append("trigger condition blank")
            detail = "rollback_plan effectively missing: " + ", ".join(missing)
        return SafetyCheck(
            id=cls._CHECK_ROLLBACK_PRESENT,
            label="Rollback plan present",
            passed=present,
            detail=detail,
        )

    @classmethod
    def _check_ttl_minutes(cls, *, strategy: DefenseStrategy) -> SafetyCheck:
        """A strategy must have a TTL of at least one minute (60 seconds).

        Anything below that is treated as "no minutes-level TTL" which
        is effectively missing for the purpose of human-approval gating.
        """
        ttl_seconds = int(strategy.ttl or 0)
        ttl_minutes = ttl_seconds // 60
        present = ttl_seconds >= 60
        if present:
            detail = f"ttl={ttl_seconds}s (~{ttl_minutes} min)"
        else:
            detail = (
                f"ttl_minutes effectively missing: ttl={ttl_seconds}s is below 60s"
                if ttl_seconds > 0
                else "ttl_minutes effectively missing: ttl is zero"
            )
        return SafetyCheck(
            id=cls._CHECK_TTL_PRESENT,
            label="TTL minutes present",
            passed=present,
            detail=detail,
        )

    @classmethod
    def _check_policy_human_approval(
        cls, *, policy_validation: PolicyValidation
    ) -> SafetyCheck:
        """Trip when policy MCP returned ``requires_human_approval=true``.

        When the MCP was not called (``mcp_called=False``) we treat this
        check as passed but explicitly note "policy not consulted" so the
        UI can show a neutral icon rather than a green check.
        """
        if not policy_validation.mcp_called:
            return SafetyCheck(
                id=cls._CHECK_POLICY_HUMAN_APPROVAL,
                label="Policy MCP human-approval flag",
                passed=True,
                detail="policy MCP not consulted",
            )
        if policy_validation.requires_human_approval:
            return SafetyCheck(
                id=cls._CHECK_POLICY_HUMAN_APPROVAL,
                label="Policy MCP human-approval flag",
                passed=False,
                detail="policy-mcp-server returned requires_human_approval=true",
            )
        return SafetyCheck(
            id=cls._CHECK_POLICY_HUMAN_APPROVAL,
            label="Policy MCP human-approval flag",
            passed=True,
            detail="policy-mcp-server returned requires_human_approval=false",
        )

    # ---- Reason aggregation + constraint surfacing --------------------------

    @staticmethod
    def _collect_approval_reasons(
        *,
        safety_checks: list[SafetyCheck],
        status: StrategyStatus,
        policy_validation: PolicyValidation,
    ) -> list[str]:
        """Build the human-readable list shown on the approval card.

        Order: each failed safety check's ``label: detail`` first, followed
        by status / policy level reasons that don't map to a single check.
        Always returns ``[]`` when nothing forces human approval — keeps the
        UI minimal on the happy path.
        """
        reasons: list[str] = [
            f"{c.label}: {c.detail}" for c in safety_checks if not c.passed
        ]
        if status == StrategyStatus.NEEDS_REVISION:
            reasons.append(
                "Policy validation failed; strategy needs revision before any execution"
            )
        elif status == StrategyStatus.REJECTED:
            reasons.append("Strategy was rejected by Coordinator")
        if (
            policy_validation.mcp_called
            and policy_validation.mcp_error
            and not any("policy" in r.lower() for r in reasons)
        ):
            reasons.append(f"policy MCP error: {policy_validation.mcp_error}")
        return reasons

    @staticmethod
    def _append_human_approval_constraints(
        constraints: list[str],
        *,
        human_approval_required: bool,
        auto_execution_allowed: bool,
        approval_reasons: list[str],
    ) -> None:
        """Push the strongest "do not auto-execute" line when applicable.

        Avoids duplicating an equivalent line that ``_append_policy_execution_constraints``
        may have already pushed (which only fires for status-driven blocking).
        """
        if auto_execution_allowed:
            return
        if not human_approval_required:
            return
        already_blocked = any(
            "auto-execution" in c.lower() and ("blocked" in c.lower() or "disabled" in c.lower())
            for c in constraints
        )
        if not already_blocked:
            top_reason = approval_reasons[0] if approval_reasons else "policy / safety check failed"
            constraints.append(
                f"Auto-execution disabled: human approval required ({top_reason})"
            )

    # ------------------------------------------------------------------
    # 拓扑/MCP 聚合辅助
    # ------------------------------------------------------------------

    @staticmethod
    def _aggregate_mcp_trace(state: DebateState) -> list[MCPToolCall]:
        """按发生顺序聚合 Planner / Red-Team 两侧的 MCP 调用。

        - 没有任何 MCP 调用时返回空数组（满足 spec：mcp_trace: []）
        - 不去重：保留每次调用的真实顺序，利于审计与前端时间线展示
        """
        trace: list[MCPToolCall] = []
        if state.plannerMetadata and state.plannerMetadata.mcp_tool_calls:
            trace.extend(state.plannerMetadata.mcp_tool_calls)
        if state.redTeamFindings and state.redTeamFindings.mcp_tool_calls:
            trace.extend(state.redTeamFindings.mcp_tool_calls)
        return trace

    @staticmethod
    def _build_topology_context_summary(state: DebateState) -> dict[str, Any]:
        """聚合 Planner + Red-Team 拓扑视角，输出供前端 / 下游消费的紧凑摘要。"""
        md: PlannerTopologyMetadata | None = state.plannerMetadata
        ft: RedTeamFindings | None = state.redTeamFindings

        used = bool(md and md.topology_context_used)
        summary: dict[str, Any] = {
            "topology_context_used": used,
            "expected_blast_radius": (md.expected_blast_radius.value if md else BlastRadius.LOW.value),
            "affected_assets": list(md.affected_assets) if md else [],
            "topology_evidence": list(md.topology_evidence) if md else [],
            "red_team": {
                "topology_findings": list(ft.topology_based_findings) if ft else [],
                "residual_attack_paths": [
                    {
                        "source": p.source,
                        "target": p.target,
                        "nodes": list(p.nodes),
                        "summary": p.summary,
                    }
                    for p in (ft.residual_attack_paths if ft else [])
                ],
                "business_impact_risks": list(ft.business_impact_risks) if ft else [],
                "recommended_constraints": list(ft.recommended_constraints) if ft else [],
            },
            "mcp_errors": [
                err for err in (
                    (md.mcp_error if md else None),
                    (ft.mcp_error if ft else None),
                )
                if err
            ],
        }
        return summary

    @staticmethod
    def _build_execution_constraints(state: DebateState) -> list[str]:
        """聚合给执行层的硬约束清单。

        来源：
          1) Red-Team recommended_constraints（已经是 actionable 的字符串）
          2) Planner expected_blast_radius=HIGH 的额外提示（要求灰度发布）
          3) 未解决挑战 -> 执行需观察 N 分钟后再扩量
        """
        constraints: list[str] = []
        ft = state.redTeamFindings
        if ft and ft.recommended_constraints:
            constraints.extend(ft.recommended_constraints)

        md = state.plannerMetadata
        if md and md.expected_blast_radius == BlastRadius.HIGH:
            constraints.append(
                "Apply with canary rollout: enable on 10% traffic for 5 minutes "
                "before full deployment due to HIGH expected blast radius"
            )

        unresolved_count = len(state.unresolvedChallenges)
        if unresolved_count > 0:
            constraints.append(
                f"Monitor {unresolved_count} unresolved challenge(s) for 10 minutes "
                f"post-deployment; auto-rollback if anomaly detected"
            )
        return constraints

    @staticmethod
    def _compute_risk_level(state: DebateState, strategy: Any) -> RiskLevel:
        """综合多维信号计算最终风险等级。

        信号权重（取最大值）：
          - SecurityEvent.severity (CRITICAL -> CRITICAL, HIGH -> HIGH, MEDIUM -> MEDIUM, LOW -> LOW)
          - PlannerTopologyMetadata.expected_blast_radius
          - RedTeamFindings: residual_attack_paths>0 -> HIGH;
                              business_impact_risks>=2 -> HIGH;
                              business_impact_risks=1 -> MEDIUM
          - SecurityEvent.riskScore >= 0.9 -> 至少 HIGH
          - 未解决挑战数 >= 3 -> 至少 MEDIUM
        """
        level = RiskLevel.LOW

        # 1) 事件 severity 直接映射
        sev_map = {
            Severity.LOW: RiskLevel.LOW,
            Severity.MEDIUM: RiskLevel.MEDIUM,
            Severity.HIGH: RiskLevel.HIGH,
            Severity.CRITICAL: RiskLevel.CRITICAL,
        }
        level = CoordinatorAgent._max_risk(level, sev_map.get(state.securityEvent.severity, RiskLevel.LOW))

        # 2) Planner blast radius
        if state.plannerMetadata:
            br = state.plannerMetadata.expected_blast_radius
            if br == BlastRadius.HIGH:
                level = CoordinatorAgent._max_risk(level, RiskLevel.HIGH)
            elif br == BlastRadius.MEDIUM:
                level = CoordinatorAgent._max_risk(level, RiskLevel.MEDIUM)

        # 3) Red-team topology signals (residual paths may stay <= MEDIUM for sandbox lows).
        ft = state.redTeamFindings
        if ft:
            if ft.residual_attack_paths:
                if CoordinatorAgent._sandbox_residual_paths_should_not_escalate_to_high(state):
                    level = CoordinatorAgent._max_risk(level, RiskLevel.MEDIUM)
                else:
                    level = CoordinatorAgent._max_risk(level, RiskLevel.HIGH)
            biz_count = len(ft.business_impact_risks)
            if biz_count >= 2:
                level = CoordinatorAgent._max_risk(level, RiskLevel.HIGH)
            elif biz_count == 1:
                level = CoordinatorAgent._max_risk(level, RiskLevel.MEDIUM)

        # 4) riskScore 高位
        if state.securityEvent.riskScore >= 0.9:
            level = CoordinatorAgent._max_risk(level, RiskLevel.HIGH)

        # 5) 未解决挑战堆积
        if len(state.unresolvedChallenges) >= 3:
            level = CoordinatorAgent._max_risk(level, RiskLevel.MEDIUM)

        return level

    @staticmethod
    def _sandbox_residual_paths_should_not_escalate_to_high(state: DebateState) -> bool:
        """Keep residual_attack_paths from forcing HIGH when blast/event tier are sandbox-low."""

        md = state.plannerMetadata
        if not md or md.expected_blast_radius != BlastRadius.LOW:
            return False
        if state.securityEvent.severity not in (Severity.LOW, Severity.MEDIUM):
            return False
        if state.securityEvent.riskScore > 0.3:
            return False
        return True

    @staticmethod
    def _has_high_tier_asset_impact_signal(state: DebateState) -> bool:
        """True when CRITICAL/HIGH-tier asset impact is indicated (blocks low-risk auto)."""

        ft = state.redTeamFindings
        if ft:
            for line in ft.topology_based_findings:
                u = line.upper()
                if "CRITICAL" in u and ("ASSET" in u or "CRITICALITY" in u or "IMPACT" in u):
                    return True
                if "HIGH" in u and "CRITICALITY" in u:
                    return True
            for line in ft.business_impact_risks:
                u = line.upper()
                if "CRITICAL" in u:
                    return True
                if "HIGH" in u and "CRITICALITY" in u:
                    return True
        if state.securityEvent.severity in (Severity.HIGH, Severity.CRITICAL):
            return True
        md = state.plannerMetadata
        return bool(md and md.expected_blast_radius == BlastRadius.HIGH)

    @staticmethod
    def _is_delete_resource_action(action: Any) -> bool:
        params = dict(action.parameters or {})
        op = str(params.get("operation") or params.get("mode") or "").lower()
        return op in {"delete", "delete_resource", "remove", "destroy"}

    @staticmethod
    def _strategy_has_blocked_destructive_actions(strategy: DefenseStrategy) -> bool:
        """Blocks auto-exec when destructive verbs appear on high-impact actions."""

        for action in strategy.actions:
            if CoordinatorAgent._is_firewall_deny_all(action):
                return True
            if CoordinatorAgent._is_scale_down_critical(action):
                return True
            if CoordinatorAgent._is_delete_resource_action(action):
                return True
        return False

    @staticmethod
    def _rollback_ttl_eligible(strategy: DefenseStrategy) -> bool:
        plan = strategy.rollbackPlan
        steps_ok = bool(plan and plan.steps)
        trigger_ok = bool(plan and (plan.triggerCondition or "").strip())
        ttl_ok = int(strategy.ttl or 0) >= 60
        return steps_ok and trigger_ok and ttl_ok

    @staticmethod
    def _is_low_risk_auto_executable(
        *,
        state: DebateState,
        strategy: DefenseStrategy,
        policy_validation: PolicyValidation,
        risk_level: RiskLevel,
    ) -> bool:
        """Predicate for sandbox/demo flows that may bypass manual approval gates."""

        if not policy_validation.mcp_called or not policy_validation.valid:
            return False
        if policy_validation.requires_human_approval:
            return False
        if state.securityEvent.severity not in (Severity.LOW, Severity.MEDIUM):
            return False
        if state.securityEvent.riskScore > 0.3:
            return False
        md = state.plannerMetadata
        if not md or md.expected_blast_radius != BlastRadius.LOW:
            return False
        if CoordinatorAgent._has_high_tier_asset_impact_signal(state):
            return False
        if risk_level not in (RiskLevel.LOW, RiskLevel.MEDIUM):
            return False
        if CoordinatorAgent._strategy_has_blocked_destructive_actions(strategy):
            return False
        if not CoordinatorAgent._rollback_ttl_eligible(strategy):
            return False
        return True

    @staticmethod
    def _max_risk(a: RiskLevel, b: RiskLevel) -> RiskLevel:
        return _RISK_REVERSE[max(_RISK_ORDER[a], _RISK_ORDER[b])]

    @staticmethod
    def _build_decision_reasoning(
        *,
        rationale: str,
        reason: str,
        unresolved_count: int,
        confidence_ok: bool,
        high_risk: bool,
        risk_level: RiskLevel,
        findings: RedTeamFindings | None,
        metadata: PlannerTopologyMetadata | None,
        status: StrategyStatus,
        policy_validation: PolicyValidation,
        safety_checks: list[SafetyCheck] | None = None,
        auto_execution_allowed: bool = True,
        human_approval_required: bool = False,
    ) -> str:
        """生成多行决策推理，便于前端在审计页直接展示。"""
        lines: list[str] = []
        lines.append(f"reason={reason}; risk_level={risk_level.value}")
        lines.append(rationale)
        lines.append(
            f"signals: high_risk={'Y' if high_risk else 'N'}, "
            f"confidence_ok={'Y' if confidence_ok else 'N'}, "
            f"unresolved={unresolved_count}"
        )
        if metadata and metadata.topology_context_used:
            lines.append(
                f"topology: blast_radius={metadata.expected_blast_radius.value}, "
                f"affected_assets={len(metadata.affected_assets)}"
            )
        if findings:
            if findings.residual_attack_paths:
                lines.append(f"residual_attack_paths={len(findings.residual_attack_paths)}")
            if findings.business_impact_risks:
                lines.append(f"business_impact_risks={len(findings.business_impact_risks)}")
        # Phase 3 signals: surface policy MCP validation outcome.
        if policy_validation.mcp_called:
            lines.append(
                f"policy: valid={policy_validation.valid}, "
                f"violations={len(policy_validation.violations)}, "
                f"warnings={len(policy_validation.warnings)}, "
                f"human_approval={policy_validation.requires_human_approval}"
            )
            if policy_validation.mcp_error:
                lines.append(f"policy_error={policy_validation.mcp_error}")
        # Phase 5 signals: human-approval boundary outcome.
        if safety_checks is not None:
            failed_ids = [c.id for c in safety_checks if not c.passed]
            lines.append(
                f"safety: total={len(safety_checks)}, "
                f"failed={len(failed_ids)}"
                + (f" ({', '.join(failed_ids)})" if failed_ids else "")
            )
            lines.append(
                f"approval: human_required={'Y' if human_approval_required else 'N'}, "
                f"auto_execution={'Y' if auto_execution_allowed else 'N'}"
            )
        lines.append(f"status={status.value}")
        return " | ".join(lines)
